julia-vscode/SymbolServer.jl

src/SymbolServer.jl
src/clientprocess/clientprocess_main.jl

Does the same thing as #9, but aligns the code more with the existing pattern.

Store caches of base/core - take 2

---

src/clientprocess/clientprocess_main.jl

While researching https://github.com/JuliaEditorSupport/LanguageServer.jl/issues/330 I've found that the server waits for response from the client process indefinitely. This is because if there is an error while loading package in the :load_package case, the stdout is still redirected while the catch block executes, which causes the client process to print nothing and, in turn, for the  master to wait for response indefinitely. This PR fixes this and makes the code little bit nicer (IMO).

Improve stdout redirection in client process

---

src/SymbolServer.jl

This should lead to crash reports including errors in the symbol server process.

Better error reporting

---

src/clientprocess/clientprocess_main.jl

Fixes https://github.com/julia-vscode/julia-vscode/issues/801.

Surpress all stdout output in symbol server process

---

src/SymbolServer.jl

Backport https://github.com/julia-vscode/SymbolServer.jl/pull/40 and https://github.com/julia-vscode/SymbolServer.jl/commit/ae8112886e879dcde0392efb062fa25034fa2cad.

Start symbol server without startup file

---

src/symbols.jl
src/utils.jl

Define is_stdlib on older Julia versions

---

src/symbols.jl
src/utils.jl

Fixes some issues, for example `Core.Symbol` was stored as having 0 methods.

simplify DataType storing

---

src/symbols.jl

remove unnecessary change of pkg env

---

README.md
src/SymbolServer.jl
src/server.jl
src/symbols.jl
src/utils.jl
test/runtests.jl
test/testenv/Manifest.toml
test/testenv/Project.toml
test/testenv/dev/TableTraits/LICENSE.md
test/testenv/dev/TableTraits/NEWS.md
test/testenv/dev/TableTraits/Project.toml
test/testenv/dev/TableTraits/README.md
test/testenv/dev/TableTraits/src/TableTraits.jl
test/testenv/dev/TableTraits/test/runtests.jl

Async citests

---

src/utils.jl

I think this is not used anywhere? Trying to get our code coverage up ;)

Remove some old code

---

src/server.jl

With this, interrupting the indexing of packages doesn't mean you've wasted your (computer's) time

Write cache after each package

---

src/symbols.jl

closes https://github.com/julia-vscode/SymbolServer.jl/issues/86

TypeRef fix

---

src/symbols.jl
src/utils.jl

This no longer seems to be used?

remove is_stdlib refs

---

src/symbols.jl

Having found out that `try` blocks don't actually add much overhead...

Add try block around caching of each symbol

---

src/server.jl

This reverts commit b9f71eb4478ba78c5990c129d5ae6c2604a69f88.

Try whether reverting fix solves CI problems

---

src/SymbolServer.jl
src/server.jl

Fixes a bug from crash reporting.

Fix usage of get_filename_from_name

---

src/server.jl

There is a bug in crash reporting that might be fixed by this. Or maybe not, but in that case it should be easier to pin down what is going on in future versions.

Only call Pkg.Types.Context() once in symserver

---

src/server.jl

Fixes https://github.com/julia-vscode/SymbolServer.jl/issues/115.

Make pkg load more robust

---

Project.toml
src/SymbolServer.jl
src/server.jl
src/symbols.jl

Mark methods as extensions of other functions

---

src/symbols.jl

fix kw caching?

---

src/SymbolServer.jl

Fixes a bug from crash reporting.

Guard against invalid project files

---

src/symbols.jl
src/utils.jl

EDIT: also added a fix for #136. This error is coming from internal C code so I can't quite tell what is triggering it - a try block seems the best approach for now.

fix typo, closes #135

---

src/symbols.jl

Not breaking but adds something so requires a minor ver bump

store list of exported names in ModuleStore

---

src/utils.jl

Fixes https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22Name%22%3A%22julia-vscode%22%2C%22SubscriptionId%22%3A%226803c4ed-bcb4-41d4-bceb-7faf5e7a3469%22%2C%22ResourceGroup%22%3A%22Default%22%7D/DataModel/%7B%22eventId%22%3A%2299840bc1-85a4-11ea-a1b0-2b33bdcdf63c%22%2C%22timestamp%22%3A%222020-04-23T20%3A54%3A02.152Z%22%2C%22cacheId%22%3A%225b4d2949-3888-4e1e-9597-1facca06e5a7%22%2C%22eventTable%22%3A%22exceptions%22%7D, hopefully.

Wrap a call that can fail in try catch

---

src/SymbolServer.jl

Fixes [this crashreport](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22Name%22%3A%22julia-vscode%22%2C%22SubscriptionId%22%3A%226803c4ed-bcb4-41d4-bceb-7faf5e7a3469%22%2C%22ResourceGroup%22%3A%22Default%22%7D/DataModel/%7B%22eventId%22%3A%225e2f29d2-84f3-11ea-a3c1-1bb1c9c0b4ea%22%2C%22timestamp%22%3A%222020-04-22T23%3A45%3A22.879Z%22%2C%22cacheId%22%3A%22ac486a8a-7fed-422d-9e0b-2fdc794659a3%22%2C%22eventTable%22%3A%22exceptions%22%7D).

Protect against a file IO error

---

src/SymbolServer.jl

First PR of a group that makes the symbol store last beyond extension version updates.

Add nothing option to store_path

---

src/faketypes.jl

Can't work out whats happening w/ #150 so here's code to help narrow it down.

determine what's going wrong here

---

src/utils.jl

- before `foo methodsfor bar` 
- after `foo methods for bar`

fix method list display

---

src/SymbolServer.jl

https://github.com/julia-vscode/julia-vscode/issues/1343#issuecomment-645482240

attempt to disable revise if loaded

---

src/symbols.jl
test/runtests.jl

:Main is now referenced within the cache Base so needs to be present

add :Main to stdlibs

---

src/symbols.jl

We will want to turn this on once we have remote indexing up and running.

propogate get_return_types

---

src/server.jl

I'm going to merge right away because the currently shipped insider build crashes from the get go because of this and this seems to fix it. Review after the fact would still be good!

Fix how server.jl loads SymbolServer.jl code

---

src/utils.jl

create dummy cache locally for downloads of unsuccessful caches

---

src/SymbolServer.jl
src/faketypes.jl
src/serialize.jl
src/utils.jl
test/runtests.jl

cosmetic changes

---

src/utils.jl

fix version check as with previous PR

---

src/SymbolServer.jl

Fixes https://github.com/julia-vscode/crashreporting-issues/issues/45 (I hope).

fix load_project_packages_into_store! for invalid Project.toml

---

src/SymbolServer.jl
src/utils.jl

by adding a bunch of `yield`s.

increase startup responsiveness

---

Project.toml

For https://github.com/julia-vscode/LanguageServer.jl/issues/998

Release 7.2.0
