src/SymbolServer.jl
src/clientprocess/clientprocess_main.jl
src/clientprocess/from_static_lint.jl

Makes this functional wrt current LanguageServer/StaticLint master. Pulls all available packages (installed + dependencies) from the default env.
I suggest we merge this and look to make a release while work on getting environments right (and other development) is ongoing. Functionality is on par with what we had before and stability is better.
On a side note, I'm noticing SymbolServer needs to be loaded in the toplevel scope for any packages that use it to be able to load stores from the disc, i.e.:
```
using LanguageServer
LanguageServer.StaticLint.SymbolServer.getstore(LanguageServer.StaticLint.SymbolServer.SymbolServerProcess())
```
failes while:
```
using LanguageServer, SymbolServer
LanguageServer.StaticLint.SymbolServer.getstore(LanguageServer.StaticLint.SymbolServer.SymbolServerPro …
```

Fixloadpath

---

src/clientprocess/clientprocess_main.jl
src/clientprocess/from_static_lint.jl

Internal representation of the Project.toml file has changed in Pkg v1.1.

fix JuliaEditorSupport/LanguageServer.jl#320

---

.travis.yml
appveyor.yml
src/SymbolServer.jl
src/clientprocess/clientprocess_main.jl
src/clientprocess/from_static_lint.jl

This commit resolves the following issues:
* UUIDs were used as keys for a `Dict{String,Any}`, leading to an exception being thrown.
* `depot["manifest"]` is now indexed by UUID instead of by name.
* `nullfile` was never closed (not strictly an issue with Julia 1.1, but the fact that output redirection was not restored lead to the silent failure / freeze with Julia 1.1)
Fixes https://github.com/JuliaEditorSupport/julia-vscode/issues/647

Restore compatibility with Julia 1.1

---

REQUIRE
src/SymbolServer.jl
src/clientprocess/clientprocess_main.jl
src/clientprocess/from_static_lint.jl
test/runtests.jl

This makes quite a few (hopefully simplifying..) changes. 
- SymbolServerProcess now holds a Pkg.Types.Context instance from the server listing available packages as well as the loaded package depot. Storing the loaded packages inside this instance is intended to allow us update them if changes are detected to disc files (i.e. environment manifest file or, for deved packages, the source files).
- I've stripped out some unneeded methods for checking available packages.
- A slightly safer approach to loading .jstore files.
- Packages are loaded using a Pkg.Type.PackageEntry rather than name/uuid combo.
- ModuleStore now includes `ver` and `sha` field. These are to be used for checking whether a cache is stale.
- `get_dir_sha` is an (extremely bad) attempt to get a unique identifier for a …

Checkdirty

---

src/symbols.jl

We've had a long standing bug when an environment contains the MOI package (https://github.com/julia-vscode/SymbolServer.jl/issues/52). Hopefully this fixes the problem for good. this also came in via crash reporting, and I was able to reproduce the error, and this fix seemed to get rid of it.

Fix world age bug

---

src/symbols.jl

Without that we seem to get a fair number of segfaults of the symbol server... Not sure what the root cause is, but this at list fixes it for now.

Fix a segfault bug

---

src/SymbolServer.jl

This is a trade-off decision we need to make.
Without this PR I get the following timings:
Index an environment where nothing is precompiled: 416 seconds
Index an environment where everything is precompiled: 196 seconds
With this PR:
Index an environment: 267 seconds
So with this PR we make the case where the precompile cache is out-of-date faster, but we make the situation where the precompile cache is up-to-date slower.
Another benefit of this PR is that we don't create precompile files, so in some sense it is less intrusive than our previous story.
Not sure whether we should do this, to be honest :) Probably yes, because it improves the worst case scenario?
Thanks @pfitzseb for suggesting this.

Remove precompile step

---

src/symbols.jl

removes `(@ref)` from documentation. I think these are used to help relate documentation objects together but aren't links.
fixes https://github.com/julia-vscode/LanguageServer.jl/issues/264

remove `ref`s from documentation

---

README.md
src/SymbolServer.jl
src/server.jl
src/symbols.jl
src/utils.jl
test/runtests.jl
test/testenv/Manifest.toml
test/testenv/Project.toml

@ZacLN this is where I am right now.
Still needs new tests, and some more methods in `utils.jl` to make it work on all Julia versions and crash reporting integration.
Fixes https://github.com/julia-vscode/SymbolServer.jl/issues/73. It now uses the tree hash, SAH of the path name or uuid for the cache filename (for normal packages, deved packages and stdlib packages respectively).

Rework API for async use

---

src/symbols.jl

Where functions are overloaded by a package this PR only stores methods associated with the package (before we would duplicate method stores for all methods - when things like `+` are extended this is significantly costly).
Note: Would require changes to StaticLint/LanguageServer logic

Don't repeatedly store methods from other modules

---

README.md
src/SymbolServer.jl
src/server.jl
test/runtests.jl

Sorry for yet another iteration, but I think it is better if we put the `@async` code entirely in the LS, that gives us much more flexibility. This design here also makes it easier to return error states etc. I'll update the corresponding LS PR next, and then you can take a look at both. In principle this doesn't change much of how things work, it really is just a bit of an API tweak and where we have the `@async` keyword.
EDIT: I've now updated https://github.com/julia-vscode/LanguageServer.jl/pull/469 to work with this PR here.

Use a different design for the async API

---

Project.toml
src/baseshow.jl
src/symbols.jl
src/utils.jl

Copies methods to display documentation, etc from /base and REPL/src/docview.jl to prevent overloading by packages (e.g. Flux defined a show method for an internal DataType that caused crashes).

copy base/stdlib doc view methods to prevent overloading

---

src/baseshow.jl

Picked up from crash reports. 
I think this should probably be the last step we take down this route in attempting to fix these issues...

Elide DocStringExtensions methods

---

src/SymbolServer.jl

Because that is actually a legit situation (for example when one hasn't installed any package yet).

Do not crash SymServ for empty env

---

src/server.jl

This fixes a problem from [crash reporting](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22Name%22%3A%22julia-vscode-dev%22%2C%22SubscriptionId%22%3A%226803c4ed-bcb4-41d4-bceb-7faf5e7a3469%22%2C%22ResourceGroup%22%3A%22Default%22%7D/DataModel/%7B%22eventId%22%3A%2221b61160-561a-11ea-8bb7-ddc181a64e4d%22%2C%22timestamp%22%3A%222020-02-23T08%3A54%3A27.232Z%22%2C%22cacheId%22%3A%22a3457294-f530-446e-8dd5-b8affab5c493%22%2C%22eventTable%22%3A%22exceptions%22%7D).
I think what is happening here is that users manually modify a `Project.toml`, i.e. they add a line there, and then the `Manifest.toml` doesn't have a corresponding entry for that package. I'm not 100% positive this PR will fix this entirely, but at least we won't crash anymore :)

Guard against a Project.toml Manifest.toml mismatch

---

src/symbols.jl

fixes https://github.com/julia-vscode/SymbolServer.jl/issues/109

check field is a Module before attempting to mark dependency link

---

src/symbols.jl

Fixes a problem seen in crash reporting.
Also removes the return value, as far as I can tell it is not used anywhere.

Don't crash when a UUID is missing in manifest

---

src/server.jl

If the current env can't be read we now no longer crash but just exit. Fixes a bug from crash reporting.

Do not crash when env can't be read

---

Project.toml
src/SymbolServer.jl
src/server.jl
src/symbols.jl

This fixes another problem from crash reporting. Sometimes the symbol server crashes with a segfault because a package that we load has some really buggy code. Our `try catch` for these situations doesn't help. In general, we don't want to send a crash report for those cases: it is not our fault, so we shouldn't count this as a failure on our end.
This PR (and the companion PRs in LS and the client) works around this by adding a back communication channel from the symbol server to the LS process. The symbol server there notifies the LS "I will try to load package X now". If the symserver then crashes, the LS knows that it was a segfault in a package and sends a special trace event via telemetry. As soon as the symserver is done loading the user package it sends a message "I'm done loading …

Add symserv progress and harden against segfaults

---

src/SymbolServer.jl

Fixes https://github.com/julia-vscode/SymbolServer.jl/issues/116. Fixes https://github.com/julia-vscode/SymbolServer.jl/issues/118. Hopefully, but in any case, this is a pretty stupid bug.

Fix pipename for symserver communication

---

src/faketypes.jl
src/symbols.jl

This reduces the amount of type information cached by only storing the name of parameters rather than the full type. For example `Union{Int, Vector{Int}}` -> `Union{Int,Vector}`. This is good enough for our uses.
Without this the loaded cache for my own environment was ~1Gb when using vscode..

Store a little less information about types

---

src/server.jl

This is a speculative fix for [this crash report](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22Name%22%3A%22julia-vscode%22%2C%22SubscriptionId%22%3A%226803c4ed-bcb4-41d4-bceb-7faf5e7a3469%22%2C%22ResourceGroup%22%3A%22Default%22%7D/DataModel/%7B%22eventId%22%3A%2217d096d3-8616-11ea-84ac-67bc3467b635%22%2C%22timestamp%22%3A%222020-04-24T10%3A28%3A39.079Z%22%2C%22cacheId%22%3A%2215585051-ec3e-4f4b-a164-ea0936c017e0%22%2C%22eventTable%22%3A%22exceptions%22%7D).

Make sure we always have access to the stdlibs in the server

---

src/symbols.jl
src/utils.jl

Adds a field to `ModuleStore` that holds used modules and make sure that a VarRef to those modules is stored in the values list.
Not necessarily breaking but will invalidate cache stores and will require a minor ver bump to make use of the new field

Store list of modules used by another

---

src/SymbolServer.jl
src/server.jl
src/symbols.jl
src/utils.jl
test/runtests.jl

Changes how symbols are cached - now caches the entire environment as existing in the symbol server process all in one go rather than trying to treat modules as separate objects (they're not). 
This appears to be significantly faster than the previous approach.
Adds a test to ensure all the symbols we need are cached.
Todo: Add test to check that  function methods are assigned to the correct FunctionStores within each module.

refactor of how symbols are pulled from packages

---

src/SymbolServer.jl
src/faketypes.jl
src/symbols.jl
src/utils.jl

I decided to see if I could determine whether there was any way to speed up LanguageServer. I'm not sure how to run it in "real" circumstances, but as a proxy I decided to profile the various files in its tests. It turns out there was exactly one obvious bottleneck: calls to `deepcopy(SymbolServer.stdlibs)`.
As a comment in this PR explains, `deepcopy` is safe and convenient but slow; its slowness comes from two factors:
- iterating over e.g., `fieldnames(typeof(x))` rather than creating a hand-crafted version for each struct type
- its mechanisms to avoid cycles when objects mutually reference each other
If you don't need to worry about cycles, you can do a *lot* better by defining your own recursive copy function, and that is done in this PR. There is a downside, mainly that as you …

Improve performance with `recursive_copy`

---

src/utils.jl

make it more consistent with Base's print:
```julia
Base.bitshow is a Function.
[1] bitshow(io::IO, B::BitArray) in Base at show.jl:2256
[2] bitshow(B::BitArray) in Base at show.jl:2265
```

show method locations

---

src/symbols.jl

`Core.Compiler.Params` doesn't exist on Julia 1.6

comment out disabled code blocks

---

docs/src/index.md
src/faketypes.jl
src/symbols.jl
src/utils.jl

~~This is "WIP" because it currently fails [two tests](https://github.com/julia-vscode/SymbolServer.jl/blob/054629cdd0aa8b937b7dda57cbc3692bf88562cd/test/runtests.jl#L42-L45) (just for a handful of `Core.Builltin`and/or `Core.Intrinsic` functions, I think). I'd appreciate some help figuring out how to fix them.~~
~~This takes two main strategies, control over specialization and greater caching, to improve package performance.~~
Several functions have to operate on arguments that have a huge number of different types: any function that takes a function or a type as an argument might, in principle, be specialized, but then used only once or a small handful of times. This marks such arguments with atsign-nospecialize annotations, to prevent them from being recompiled many times over.  Since …

Improve performance with less specialization

---

src/faketypes.jl
src/server.jl
src/symbols.jl
src/utils.jl
test/runtests.jl

This rips off most of @timholy's caching approach, from an earlier PR but ensures we pull in all the variables needed (including, inter alia, some imported and using'ed variables). It also fixes a bug whereby within a module a lot of symbols were being stored when they didn't need to be.
Speedup is ~3x for caching some arbitrary packages on my machine.

Performance improvements

---

src/SymbolServer.jl
src/symbols.jl
src/utils.jl

This adds a few optimizations that drop the time spent on the same workload described in the OP of #160 from 25.2s to 21.0s.
However, I think the "unsorted_names" is kind of a red herring, and I won't be remotely offended if you decide to just close this and go a different way. From a broader perspective, my sense is that `split_module_names` is doing something quite inefficient. It accounts for more than one-third of the total run time, and for comparison:
```julia
julia> using Images, Profile, ProfileView  # same workload as in #160
Gtk-Message: 06:47:57.888: Failed to load module "canberra-gtk-module"
Gtk-Message: 06:47:57.889: Failed to load module "canberra-gtk-module"
julia> using MethodAnalysis
julia> const allnames = Symbol[]
Symbol[]
julia> @time visit() do item
if item isa …
```

Add a couple of small performance tweaks

---

src/symbols.jl

Reverts to previous handling of `include` before the slight refactor. This approach is obviously wrong - `Base.include` is not exported - and will be changed in the future.

export `include` from Base cache

---

Project.toml
src/symbols.jl

Currently the locations of symbols in standard library are invalid for julia that is not built from source. E.g. `LinearAlgebra.eigen`'s location would be `/Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/InteractiveUtils/src/InteractiveUtils.jl:53` on macOS.
This is because of https://github.com/JuliaLang/julia/issues/26314 and I'm trying to fix this borrowing [the code in CodeTracking.jl to fix this issue](https://github.com/timholy/CodeTracking.jl/blob/afc73a957f5034cc7f02e084a91283c47882f92b/src/utils.jl#L87-L122).
@ZacLN is my understanding correct that SymbolServer only collects locations of methods, right ? Otherwise we need to use this kind of patching for other places as well.

fix paths of symbols in stdlibs

---

src/symbols.jl

The newly added `all_names` has a few advantages over `split_module_names`:
1. Seems to be about an order (or two) of magnitude faster:
```
julia> @time all_names(JSON);
0.000248 seconds (51 allocations: 7.281 KiB)
julia> @time SymbolServer.split_module_names(JSON, allns);
0.015986 seconds (19.93 k allocations: 1.255 MiB)
```
2. It seems to be more correct (in this specific case its `Base.parse` being shadowed by `JSON.Parsers.parse`, which is imported into `JSON` with `using .Parsers: parse`):
```
julia> :parse in all_names(JSON)
true
julia> a, b = SymbolServer.split_module_names(JSON, allns);
julia> :parse in a || :parse in b
false
```
This is only a very superficial integration of that function, mostly because I'm not 100% confident I haven't missed anything and would like to hear …

improved name resolution

---

src/utils.jl

This seems to fix https://github.com/julia-vscode/LanguageServer.jl/issues/840 for me locally

Check if submod.vals has key before retrieving

---

.github/workflows/jlpkgbutler-ci-master-workflow.yml
.github/workflows/jlpkgbutler-ci-pr-workflow.yml
src/faketypes.jl
src/symbols.jl
src/utils.jl
test/runtests.jl

see https://github.com/JuliaLang/julia/pull/38835 and https://github.com/JuliaLang/julia/pull/38136

fix on Julia nightly

---

src/symbols.jl
test/runtests.jl

Makes sure we don't overwrite FunctionStores in a module that contributes methods to an imported function.

closes vscode issue #1832

---

src/utils.jl

Should fix a 
```
ERROR: LoadError: MethodError: Cannot `convert` an object of type Text{String} to an object of type String
Closest candidates are:
convert(::Type{String}, !Matched::CategoricalArrays.CategoricalValue) at C:\Users\...\.julia\packages\CategoricalArrays\0ZAbp\src\value.jl:60
convert(::Type{String}, !Matched::FilePathsBase.AbstractPath) at C:\Users\...\.julia\packages\FilePathsBase\9nTwN\src\path.jl:112
convert(::Type{String}, !Matched::LibPQ.PQValue) at C:\Users\...\.julia\packages\LibPQ\LSA5x\src\parsing.jl:105
...
Stacktrace:
[1] Main.SymbolServer.FunctionStore(::Main.SymbolServer.VarRef, ::Array{Main.SymbolServer.MethodStore,1}, ::Text{String}, ::Main.SymbolServer.VarRef, ::Bool) at c:\Users\...\.vscode-insiders\extensions\julialang.language-julia-insider-1.0.10\scripts\p …
```

make sure `_doc` always returns a String

---

src/utils.jl

Add's a missing recursive_copy method. Could possibly add a fallback method that masks `deepcopy`?

add recursive_copy method

---

src/faketypes.jl

See https://github.com/JuliaLang/julia/pull/39239#issuecomment-760016914
`Core.TypeofVararg` introduced in https://github.com/JuliaLang/julia/pull/3813
`VERSION >= v"1.7.0-DEV.77"`

Refer to Core.TypeofVararg as typeof(Vararg)

---

.gitignore
registryindexer/Dockerfile
registryindexer/Manifest.toml
registryindexer/Project.toml
registryindexer/main.jl
src/indexbasestdlib.jl
src/indexpackage.jl

Very WIP. Some things that still need to be done:

Add registry indexer

---

src/SymbolServer.jl
src/server.jl
src/utils.jl
test/runtests.jl

A first draft of how this may look on the client side- thoughts?

Retrieve remote caches

---

src/utils.jl

Fixes https://github.com/julia-vscode/crashreporting-issues/issues/27.
At least I think it does? I would have expected the old version of the code to actually be a syntax error?

Fix a typo

---

src/symbols.jl

For next minor - stores methods for datatypes that have been imported into a module and rebound under a new name. 
For next minor version rather than patch.
Fixes one of the issues in https://github.com/julia-vscode/julia-vscode/issues/1224

store methods for shadowed datatypes

---

src/indexpackage.jl

Runs inference on all methods when we're caching them (costly)

turn on get_return_types in indexpackage.jl

---

src/utils.jl

Fixes issue linked to https://github.com/julia-vscode/SymbolServer.jl/pull/229

make `read_manifest` slightly more robust

---

src/utils.jl

Fixes https://github.com/julia-vscode/crashreporting-issues/issues/41.
Fixes https://github.com/julia-vscode/crashreporting-issues/issues/42.
We don't care about any errors in that call to `Pkg.API.read_manifest` -- there's nothing we can do about them and no way to recover from them more gracefully.

fix read_manifest

---

src/SymbolServer.jl
src/serialize.jl
src/server.jl
src/utils.jl

This makes sure that task switches can happen during deserialization, so the LS doesn't appear unresponsive. It also speeds up deserialization by a factor of 10 to 20 for e.g. CUDA.jl. Lastly, progress reporting now includes a rough percentage and more info as to what's actually going on (instead of the generic "indexing packages...").

Speed up deserialization, improve progress reporting, add yield point

---

src/symbols.jl
src/utils.jl
test/runtests.jl

This adds documentation for UnionAlls, Union types, and Modules. Also, aliases will have documentation that is associated with them and not from of whatever they are aliasing.
Fixes https://github.com/julia-vscode/julia-vscode/issues/2564.

Fix missing docs for some symbols

---

test/runtests.jl

`Pair` was moved to `Core` from `Base` in 1.7, apparently.

Fix a test on Julia 1.7

---

src/SymbolServer.jl

This is something that showed up in crash reports. The old version essentially didn't take into account that the `_downloads` folder will be accessed from multiple VS Code instances at the same time and then crashed when multiple instances tried to simultaneously remove it.

Fix a race condition

---

src/server.jl

This reverts part of commit 50521fb.
Fixes [vscode#2565](https://github.com/julia-vscode/julia-vscode/issues/2565) and the problems related to DataFrames reported in comments to [vscode#1576](https://github.com/julia-vscode/julia-vscode/issues/1576)

Bugfix: methods added to functions in other packages missing in cache

---

src/SymbolServer.jl
src/utils.jl
test/runtests.jl

Given non-General packages don't have symbol caches, don't request them, to avoid requesting URLs that include the UUID & name of private packages.
Also the download batching didn't make sense to me. It seems better to limit the concurrent number of downloads, rather than the total number of batches. Update: Now batches of 100
Fixes #.

Symbol caches: Larger download batching. Don't ask for non-General pkgs

---

src/symbols.jl

The corruption is reproducible in my setup, unfortunately I don't have a MWE. But I have a stack trace:
```
ERROR: BoundsError: attempt to access 0-element Vector{Any} at index [1]
Stacktrace:
[1] getindex
@ .\array.jl:924 [inlined]
[2] resolve_getfield(x::CSTParser.EXPR, parent::SymbolServer.DataTypeStore, state::StaticLint.Delayed)
@ StaticLint c:\Users\kirby\MyDrive\Documents\julia-vscode\scripts\packages\StaticLint\src\references.jl:273
[3] resolve_getfield(x::CSTParser.EXPR, b::StaticLint.Binding, state::StaticLint.Delayed)
@ StaticLint c:\Users\kirby\MyDrive\Documents\julia-vscode\scripts\packages\StaticLint\src\references.jl:226
[4] resolve_getfield(x::CSTParser.EXPR, scope::StaticLint.Scope, state::StaticLint.Delayed)
@ StaticLint …
```

detects rare cache corruption issue and allows SymbolServer to recalculate

---

src/faketypes.jl

Fix the VSCode extension on julia master.
I just updated julia and the extension crashed with the following stacktrace:
<details>
<summary>Stacktrace</summary>
```
ERROR: LoadError: (Core, Module)
Stacktrace:
[1] error(s::Tuple{Module, DataType})
@ Base ./error.jl:44
[2] SymbolServer.FakeTypeName(x::Any; justname::Bool)
@ SymbolServer ~/.vscode/extensions/julialang.language-julia-1.54.2/scripts/packages/SymbolServer/src/faketypes.jl:43
[3] _parameter(p::Any)
@ SymbolServer ~/.vscode/extensions/julialang.language-julia-1.54.2/scripts/packages/SymbolServer/src/faketypes.jl:73
[4] SymbolServer.FakeTypeName(x::Any; justname::Bool)
@ SymbolServer ~/.vscode/extensions/julialang.language-julia-1.54.2/scripts/packages/SymbolServer/src/faketypes.jl:30
[5] FakeTypeName
@ SymbolServer …
```

Accept Module in FakeTypeName

---

src/SymbolServer.jl

Use a different version number for the LS and SSP

---

src/SymbolServer.jl

We actually don't need to run the binary at all to get the version, we have that upstream already.

Expect version of Julia.exe as argument
